const rentcondotype = {
  POST_CONDOROOM_START: 'POST_CONDOROOM_START',
  POST_CONDOROOM_FAILURE: 'POST_CONDOROOM_FAILURE',
  POST_CONDOROOM_SUCCESS: 'POST_CONDOROOM_SUCCESS',
  
  UPDATE_CONDOROOM_START: 'UPDATE_CONDOROOM_START',
  UPDATE_CONDOROOM_FAILURE: 'UPDATE_CONDOROOM_FAILURE',
  UPDATE_CONDOROOM_SUCCESS: 'UPDATE_CONDOROOM_SUCCESS',
  
  DELETE_CONDOROOM_START: 'DELETE_CONDOROOM_START',
  DELETE_CONDOROOM_FAILURE: 'DELETE_CONDOROOM_FAILURE',
  DELETE_CONDOROOM_SUCCESS: 'DELETE_CONDOROOM_SUCCESS',

  READ_CONDOROOM_START: 'READ_CONDOROOM_START',
  READ_CONDOROOM_FAILURE: 'READ_CONDOROOM_FAILURE',
  READ_CONDOROOM_SUCCESS: 'READ_CONDOROOM_SUCCESS',
};

export default rentcondotype